apiVersion: v2
name: polls
description: A Helm chart for the java spring example application

type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
- name: postgresql
  version: 10.16.2
  repository: https://charts.bitnami.com/bitnami